image: node

pages:
  stage: deploy
  script:
    - mkdir public
    - cp index.html style.css resume.html resume.css resume.md resume.pdf public/
  artifacts:
    paths:
    - public
  only:
  - master
